server:
  port: 8761
spring:
  application:
    name: ggb-register
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://localhost:8761
  server:
    waitTimeInMsWhenSyncEmpty: 5
    enable-self-preservation: true # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 60000 # 清理间隔（单位毫秒，默认是60*1000）